import React, { useState } from 'react';
import { View, Text, StyleSheet, Pressable, ScrollView, TextInput, ActivityIndicator } from 'react-native';
import { useSelector } from 'react-redux';
import { RootState } from '../../store';
import { colors } from '../../theme/colors';
import { Card } from '../../components/Card';
import { ArrowLeft, Sparkles, BookOpen, FileText, CheckCircle2, ChevronRight } from 'lucide-react-native';

interface TeacherAIToolsScreenProps {
  onBack: () => void;
}

export const TeacherAIToolsScreen: React.FC<TeacherAIToolsScreenProps> = ({ onBack }) => {
  const isDarkMode = useSelector((state: RootState) => state.theme.isDarkMode);
  const theme = isDarkMode ? colors.dark : colors.light;

  const [activeTool, setActiveTool] = useState<string | null>(null);
  const [topic, setTopic] = useState('Fractions Addition');
  const [grade, setGrade] = useState('Class 6');
  const [difficulty, setDifficulty] = useState('Medium');
  const [studentName, setStudentName] = useState('Vihaan Yadav');
  
  const [generating, setGenerating] = useState(false);
  const [generatedResult, setGeneratedResult] = useState('');

  const tools = [
    { id: 'homework', name: 'Generate Homework', desc: 'Create conceptual homework assignments', icon: FileText },
    { id: 'quiz', name: 'Generate Quiz', desc: 'Build multiple-choice quiz questions', icon: Sparkles },
    { id: 'qpaper', name: 'Generate Question Paper', desc: 'Draft slip tests and quarterly exams', icon: FileText },
    { id: 'lesson', name: 'Generate Lesson Plan', desc: 'Detailed structured teaching objectives', icon: BookOpen },
    { id: 'remarks', name: 'Report Remarks', desc: 'Draft student card comments', icon: Sparkles },
    { id: 'feedback', name: 'Parent Feedback', desc: 'Formulate parent-teacher review comments', icon: Sparkles },
    { id: 'remedial', name: 'Remedial Plan', desc: 'Plan study paths for struggling students', icon: BookOpen },
    { id: 'worksheet', name: 'Generate Worksheet', desc: 'Create visual mathematical exercises', icon: FileText },
    { id: 'project', name: 'Project Ideas', desc: 'Develop assignments and research topics', icon: BookOpen },
    { id: 'parent_comm', name: 'Parent Remarks (Stats-based)', desc: 'Remarks tailored to student performance', icon: Sparkles },
  ];

  const handleGenerate = () => {
    if (!topic && activeTool !== 'parent_comm') {
      return alert('Please enter a topic name');
    }
    setGenerating(true);
    setGeneratedResult('');
    
    setTimeout(() => {
      let result = '';
      if (activeTool === 'homework') {
        result = `### AI GENERATED MATHEMATICS HOMEWORK: ${topic} (${grade})\n\n` +
                 `**Objective**: Complete the following fractional operations. Show all intermediate steps.\n\n` +
                 `1. Add: 3/4 + 1/2. Express the result as a mixed fraction.\n` +
                 `2. Subtract: 5/6 - 2/3. Simplify to lowest terms.\n` +
                 `3. Word Problem: Aarav ate 2/5 of a pizza, and Sai ate 1/4 of the same pizza. What fraction of the pizza did they eat combined? How much pizza is left?\n\n` +
                 `*Generated by VBV AI Assistant on ${new Date().toLocaleDateString()}*`;
      } else if (activeTool === 'quiz') {
        result = `### AI GENERATED MCQS: ${topic} (${grade})\n\n` +
                 `**Q1. What is the sum of 1/3 and 2/5?**\n` +
                 `  A) 3/8\n` +
                 `  B) 11/15 (Correct)\n` +
                 `  C) 3/15\n` +
                 `  D) 2/15\n\n` +
                 `**Q2. Which of the following is equivalent to 6/8?**\n` +
                 `  A) 3/4 (Correct)\n` +
                 `  B) 12/24\n` +
                 `  C) 9/16\n` +
                 `  D) 5/8\n\n` +
                 `*Generated by VBV AI Assistant*`;
      } else if (activeTool === 'qpaper') {
        result = `### UNIT ASSESSMENT TEST PAPER: ${topic} (${grade})\n` +
                 `**Max Marks**: 25 | **Time**: 45 Mins\n\n` +
                 `**Section A: Fill in blanks (3 Marks)**\n` +
                 `1. A fraction where numerator is greater than denominator is called a _______.\n\n` +
                 `**Section B: Short Answer (12 Marks)**\n` +
                 `2. Convert 17/5 into a mixed number.\n` +
                 `3. Compare 7/9 and 5/6 using appropriate comparison symbol.\n\n` +
                 `**Section C: Long Answer (10 Marks)**\n` +
                 `4. Explain the process of finding Common Denominator using a real-world example.\n\n` +
                 `*Generated by VBV AI Assistant*`;
      } else if (activeTool === 'lesson') {
        result = `### AI TEACHING LESSON PLAN: ${topic} (${grade})\n` +
                 `**Syllabus Focus**: NCERT Chapter 4 Class VI Math\n\n` +
                 `* **Concept Outline**: Introduce Equivalent Fractions visually.\n` +
                 `* **Learning Target**: Express any fraction in its simplest equivalent form.\n` +
                 `* **Teaching Aids**: Whiteboard drawings, fraction circle cutouts.\n` +
                 `* **Activities**: Student matching game (match equivalent fraction card pairs).\n` +
                 `* **Assessment**: Quick 5-min exit slip check.\n\n` +
                 `*Generated by VBV AI Assistant*`;
      } else if (activeTool === 'remedial') {
        result = `### REMEDIAL ACTION PLAN FOR ${studentName}\n` +
                 `**Focus Area**: ${topic} Math backlog.\n\n` +
                 `1. **Diagnostic Assessment**: Review basic division tables. (Day 1)\n` +
                 `2. **Conceptual Review**: Re-teach finding Lowest Common Multiple (LCM) visually using number lines. (Day 2-3)\n` +
                 `3. **Scaffolded Exercises**: Provide 5 fraction additions with identical denominators, transitioning to unequal denominators. (Day 4-5)\n` +
                 `4. **Peer Study**: Partner with Sai Krishna for algebraic fraction reviews. (Ongoing)\n\n` +
                 `*Generated by VBV AI Assistant*`;
      } else if (activeTool === 'worksheet') {
        result = `### STUDENT WORKSHEET: ${topic}\n` +
                 `Name: ______________________  Roll No: ______\n\n` +
                 `[ ] [ ] [ ] [ ]  ➔ Shade 3/4 of this grid box.\n` +
                 `[ ] [ ] [ ] [ ] [ ] [ ] ➔ Shade 4/6 of this grid box.\n\n` +
                 `Solve:\n` +
                 `1) 1/8 + 3/8 = ______\n` +
                 `2) 5/12 + 1/6 = ______\n` +
                 `3) 7/10 - 2/5 = ______\n\n` +
                 `*Generated by VBV AI Assistant*`;
      } else if (activeTool === 'project') {
        result = `### PROJECT ASSIGNMENT IDEAS: ${topic}\n\n` +
                 `1. **Fractions in the Kitchen**: Students bake a simple recipe and document how doubling or halving ingredients changes the fractions (e.g. mixed numbers, ounces). Submit report with photo.\n` +
                 `2. **Fraction City Grid Map**: Draw a city map on grid paper. Calculate fractions of area covered by residential buildings (e.g. 3/10), roads (e.g. 1/5), parks (e.g. 1/10). Calculate total map coverage.\n\n` +
                 `*Generated by VBV AI Assistant*`;
      } else if (activeTool === 'parent_comm') {
        result = `### AUTOMATED PARENT REPORT CARD FEEDBACK: ${studentName}\n` +
                 `**Performance Index**: Low Marks (52%) | Missing Homework\n\n` +
                 `*Dear Parent, ${studentName} is showing creative potential but requires structured help in Mathematics. Currently, his scores stand at 52% due to unfinished chapter worksheets. I recommend reviewing his daily homework diary. We have formulated a Remedial Action Plan in school. Your support in checking his progress at home will greatly accelerate his results.*`;
      } else {
        result = `### GENERAL FEEDBACK: ${topic}\n\n` +
                 `Generated generic remarks on topic: ${topic}. Student performance is improving steadily. Recommended study time 2 hours daily.`;
      }
      
      setGeneratedResult(result);
      setGenerating(false);
    }, 1200);
  };

  return (
    <View style={styles.container}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
        
        {/* ================= HEADER ================= */}
        <View style={styles.subScreenHeader}>
          <Pressable onPress={activeTool ? () => { setActiveTool(null); setGeneratedResult(''); } : onBack} style={[styles.backBtn, { borderColor: theme.border }]}>
            <ArrowLeft size={18} color="#F59E0B" />
          </Pressable>
          <View style={{ flex: 1, marginLeft: 12 }}>
            <Text style={[styles.subScreenTitle, { color: theme.text }]}>AI Educational Suite</Text>
            <Text style={[styles.subScreenSubtitle, { color: theme.textSecondary }]}>
              {activeTool ? `AI Tool / ${tools.find(t => t.id === activeTool)?.name}` : 'Select AI Assistant Helper'}
            </Text>
          </View>
        </View>

        {/* ================= TOOLS SELECTION GRID ================= */}
        {!activeTool && (
          <View style={styles.toolsList}>
            {tools.map(tool => {
              const ToolIcon = tool.icon;
              return (
                <Pressable
                  key={tool.id}
                  onPress={() => setActiveTool(tool.id)}
                  style={[styles.toolCard, { backgroundColor: theme.surface, borderColor: theme.border }]}
                >
                  <View style={[styles.iconBg, { backgroundColor: '#F59E0B15' }]}>
                    <ToolIcon size={20} color="#F59E0B" />
                  </View>
                  <View style={{ flex: 1, marginLeft: 12 }}>
                    <Text style={[styles.toolName, { color: theme.text }]}>{tool.name}</Text>
                    <Text style={[styles.toolDesc, { color: theme.textSecondary }]}>{tool.desc}</Text>
                  </View>
                  <ChevronRight size={16} color={theme.textSecondary} />
                </Pressable>
              );
            })}
          </View>
        )}

        {/* ================= ACTIVE AI TOOL INPUT FORM ================= */}
        {activeTool && (
          <View>
            <Card style={styles.generatorFormCard}>
              <Text style={[styles.formLabel, { color: theme.text }]}>Parameters Configuration</Text>
              
              {activeTool === 'remedial' || activeTool === 'parent_comm' ? (
                <>
                  <Text style={[styles.inputLabel, { color: theme.textSecondary }]}>Student Name</Text>
                  <TextInput
                    style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]}
                    placeholder="Enter student name..."
                    placeholderTextColor={theme.textSecondary}
                    value={studentName}
                    onChangeText={setStudentName}
                  />
                </>
              ) : null}

              {activeTool !== 'parent_comm' && (
                <>
                  <Text style={[styles.inputLabel, { color: theme.textSecondary }]}>Topic Name</Text>
                  <TextInput
                    style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]}
                    placeholder="e.g. Fractions Addition, Decimals"
                    placeholderTextColor={theme.textSecondary}
                    value={topic}
                    onChangeText={setTopic}
                  />
                </>
              )}

              <View style={styles.formRow}>
                <View style={{ flex: 1, marginRight: 6 }}>
                  <Text style={[styles.inputLabel, { color: theme.textSecondary }]}>Class Grade</Text>
                  <TextInput
                    style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]}
                    value={grade}
                    onChangeText={setGrade}
                  />
                </View>
                <View style={{ flex: 1, marginLeft: 6 }}>
                  <Text style={[styles.inputLabel, { color: theme.textSecondary }]}>Complexity</Text>
                  <TextInput
                    style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]}
                    value={difficulty}
                    onChangeText={setDifficulty}
                  />
                </View>
              </View>

              <Pressable 
                onPress={handleGenerate}
                disabled={generating}
                style={[styles.generateBtn, { backgroundColor: '#F59E0B' }]}
              >
                {generating ? (
                  <ActivityIndicator size="small" color="#fff" />
                ) : (
                  <>
                    <Sparkles size={16} color="#fff" style={{ marginRight: 6 }} />
                    <Text style={styles.generateBtnText}>Generate Lesson/Asset</Text>
                  </>
                )}
              </Pressable>
            </Card>

            {/* AI result display */}
            {generating && (
              <View style={styles.thinkingContainer}>
                <ActivityIndicator size="large" color="#F59E0B" />
                <Text style={[styles.thinkingText, { color: theme.textSecondary }]}>VBV AI model thinking... assembling materials</Text>
              </View>
            )}

            {generatedResult ? (
              <Card style={[styles.resultCard, { borderColor: '#F59E0B30' }]}>
                <View style={styles.resultHeader}>
                  <Sparkles size={14} color="#F59E0B" />
                  <Text style={[styles.resultTitle, { color: theme.text }]}>Generated Asset Roster</Text>
                </View>
                
                <ScrollView style={styles.resultScroll}>
                  <Text style={[styles.resultText, { color: theme.text }]}>
                    {generatedResult}
                  </Text>
                </ScrollView>

                {/* Integration button */}
                <Pressable 
                  onPress={() => alert('Content copied to clipboard & loaded into lesson report draft.')}
                  style={[styles.useContentBtn, { backgroundColor: colors.success }]}
                >
                  <CheckCircle2 size={14} color="#fff" style={{ marginRight: 6 }} />
                  <Text style={styles.useContentBtnText}>Use AI Generated Content</Text>
                </Pressable>
              </Card>
            ) : null}
          </View>
        )}

      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 90,
  },
  subScreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subScreenTitle: {
    fontSize: 18,
    fontWeight: '800',
  },
  subScreenSubtitle: {
    fontSize: 11,
    fontWeight: '600',
  },
  toolsList: {
    marginTop: 8,
  },
  toolCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    marginBottom: 12,
    shadowColor: 'rgba(0,0,0,0.01)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  iconBg: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolName: {
    fontSize: 13,
    fontWeight: '800',
  },
  toolDesc: {
    fontSize: 10,
    marginTop: 1,
  },
  generatorFormCard: {
    padding: 16,
    marginVertical: 0,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 8,
  },
  input: {
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    fontSize: 12,
    marginBottom: 8,
  },
  formRow: {
    flexDirection: 'row',
  },
  generateBtn: {
    height: 44,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  generateBtnText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  thinkingContainer: {
    alignItems: 'center',
    padding: 30,
  },
  thinkingText: {
    fontSize: 11,
    fontWeight: '700',
    marginTop: 10,
  },
  resultCard: {
    padding: 16,
    marginTop: 16,
    borderWidth: 1.5,
  },
  resultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 8,
    marginBottom: 10,
  },
  resultTitle: {
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 6,
  },
  resultScroll: {
    maxHeight: 250,
  },
  resultText: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: 'Courier', // monospaced style on supported screens
  },
  useContentBtn: {
    height: 42,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  useContentBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  }
});
